spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/graysea}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:123456}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:graysea123}

server:
  port: 8080
